import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Trang chủ</h1>
          <div>
            <button>
              <i className="fa-solid fa-sign-out-alt"></i>
            </button>
          </div>
        </header>
        {children}
        <footer className="p-4 bg-gray-100 text-center">
          <p>© 2025 My Website</p>
        </footer>
      </body>
    </html>
  );
}
